# Generated by Django 3.2.9 on 2024-12-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HunterStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hunter_avatar', models.TextField()),
                ('hunter_name', models.CharField(max_length=50)),
                ('win_ratio', models.FloatField()),
                ('top_five_ratio', models.FloatField()),
                ('pick_rate', models.FloatField()),
                ('average_rank', models.IntegerField()),
                ('total_pick_number', models.IntegerField()),
                ('total_match', models.IntegerField()),
                ('average_kd_rate', models.FloatField()),
                ('average_kill_rate', models.FloatField()),
                ('average_death_rate', models.FloatField()),
                ('meta_tag', models.TextField()),
            ],
        ),
    ]
