# Generated by Django 3.2.9 on 2024-12-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hunterstatistics',
            old_name='average_death_rate',
            new_name='win_rate',
        ),
        migrations.RemoveField(
            model_name='hunterstatistics',
            name='average_kill_rate',
        ),
        migrations.RemoveField(
            model_name='hunterstatistics',
            name='top_five_ratio',
        ),
        migrations.RemoveField(
            model_name='hunterstatistics',
            name='total_match',
        ),
        migrations.RemoveField(
            model_name='hunterstatistics',
            name='total_pick_number',
        ),
        migrations.RemoveField(
            model_name='hunterstatistics',
            name='win_ratio',
        ),
        migrations.AlterModelTable(
            name='hunterstatistics',
            table='hunter_statistics',
        ),
    ]
