# Generated by Django 5.1 on 2024-12-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistic", "0002_auto_20241210_1549"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hunterstatistics",
            name="average_rank",
            field=models.FloatField(),
        ),
    ]
